### ISSUE TITLE
config.plist文件出现“1308行错误”？

### ISSUE THREAD

**Issue by kevin-Curry** [ilharp/surface-pro-4-hackintosh-monterey#11]
什么情况 说“1308行dict错误”让我无法编辑config.plist文件 我是surface book 1 Big Sur 11.2.3 用的v3版本

**Comment by kevin-Curry** [comment]
OpenCore Configurator was unable read because it isn’t in the correct format.

Please fix the following code before saving: Found non-key inside <dict> at line 1269

**Comment by ilharp** [comment]
未能及时回复十分抱歉。经检查，v3 版本的 1308 行和 v4 版本的 1269 行确实出现了错误。

你现在可以使用 v4 版本正常启动吗？我预计会在 v4 分支修复这个 bug 并发布。后续的更新和 bug 修复也将在 v4 版本上进行，v3 仅作为历史存档。

**Comment by ilharp** [comment]
已经提交了修复。你可以试一下 [这个版本（点击下载）](https://github.com/ilharp/surface-pro-4-hackintosh-monterey/archive/abd81a2cfd18a221ec0d1428c7abf6d922640172.zip) 吗？如果这个版本可以解决你的问题，我会发布 v5 作为 bugfix 版本。

**Comment by kevin-Curry** [comment]
可以启动了

**Comment by ilharp** [comment]
v5 已经发布。

**Comment by kevin-Curry** [comment]
great
