### ISSUE TITLE
pro4 i7版本不兼容

### ISSUE THREAD

**Issue by KillerJmc** [ilharp/surface-pro-4-hackintosh-monterey#5]
您好，i7+256G版本的pro4能安装monterey系统，但最后卡在MacOS的开机引导页面
![Uploading 20220521_181910.jpg…](开机引导页面)
，最后就一直无限重启了。

**Comment by ilharp** [comment]
图片没有成功上传哦~可以尝试重新上传~

**Comment by ilharp** [comment]
也可以先参考 [Dortania 的疑难解答](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html) 先自己排查一下错误哦~

**Comment by KillerJmc** [comment]
![20220521_181910](https://user-images.githubusercontent.com/57487468/169652079-04c612d5-33f9-45c6-94ee-c56922b63408.jpg)

**Comment by ilharp** [comment]
哈哈，我就猜到是这个问题

[Dortania 的这里](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/userspace-issues.html#macos-frozen-right-before-login) 有非常详细的解答哦~

**Comment by ilharp** [comment]
这个问题在 Skylake 上还是比较常见的，此前也有过 sp4 触发 TSC 相关的问题。

之前我曾经把 TSC 加装到本 repo 的 OC 上去过的，后面我看我的电脑不需要 TSC 就把他拆下来了

那我现在把 TSC 加回去好了  我一会可以发个新版本

**Comment by KillerJmc** [comment]
哇感谢大佬！

**Comment by ilharp** [comment]
可以测试一下 [这个版本](https://github.com/ilharp/surface-pro-4-hackintosh-monterey/archive/dda837c4bf170b88a8168fc2adc656aacd90aea9.zip) 吗？

如果这个版本没有问题我就把他作为稳定版发布  如果还有问题的话我会再出一个版本

如果能正常启动的话，走完 OOBE，进系统里逛一圈，然后关机，再开机，再系统里玩玩，不会卡死重启的话就说明没有问题了

**Comment by KillerJmc** [comment]
没问题，我马上测试！

**Comment by KillerJmc** [comment]
我重新安装了系统，一样的问题，这次甚至还没点击下一步就重启了，然后就一直这样😥

**Comment by KillerJmc** [comment]
他是卡住在那一小会，然后自动重启
或者刚一进去就立马重启了

**Comment by ilharp** [comment]
好的~那么可以测试一下 [这个版本](https://github.com/ilharp/surface-pro-4-hackintosh-monterey/archive/0997f86718c328fdee8e2e03658a87d74dab9ed8.zip) 吗？

如果这个版本没有问题就作为稳定版发布 如果还有问题的话还有另外一个版本可以试

另外其实系统是已经正确安装进了里面的，所以我觉得更换完 OC 以后应该是不需要重启系统的   可以直接 U 盘启动 OC 引导进入安装好的系统测试~

**Comment by KillerJmc** [comment]
好的，我等会就继续测试！

**Comment by KillerJmc** [comment]
还是不行，一样的问题😭

**Comment by ilharp** [comment]
好的~那么可以测试一下 [这个版本](https://github.com/ilharp/surface-pro-4-hackintosh-monterey/archive/c8741d380ee2ea9ac10d098bebe657a99f6a44a6.zip) 吗？

这个版本如果遇到问题的话，要看清楚是在进入系统后几秒内重启  还是在开机过程中重启的

**Comment by KillerJmc** [comment]
还是这个问题，一次在进入系统后选择国家和地区拖动滚轮时卡住重启的，另一次是在进入系统鼠标刚出现时重启的。

**Comment by ilharp** [comment]
基本可以确定是 TSC 问题了。

现在你有三个选择：

1. 回退 Big Sur，现在 repo 里的 `v4` 版本应该可以在 Big Sur 上正常工作

2. 如果你确实想解决这个问题，你可以向 acidanthera 提交 bug。你必须先按照 Dortania 提供的 [OpenCore Debugging](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html) 获得你报错的完整日志，然后用英语向 acidanthera 提交 issue。如果你希望这么做的话可以去开 issue，我会在下方帮你附加一些信息。

3. 可以加装 `cpus=1` 参数，使用单核的 CPU 进行工作。你的电脑将永远工作在单个核心上（二分之一性能），因此不推荐

可以根据需求自行选择。还有疑惑的话可以继续跟我说。

**Comment by KillerJmc** [comment]
嗯我尝试一下回退Big Sur。

**Comment by KillerJmc** [comment]
回退完毕后仍出现相同的问题，OOBE时候重启。

**Comment by ilharp** [comment]
这就奇怪了……那试试 v3 呢？

按理来说 Intel 6 代的 CPU 不会出现 TSC 问题的，这个情况很奇怪啊  并且我觉得也不像是 TSC 以外的问题

如果 v3 还有问题的话我一会给你做个 v3/v4 加装 TSC 修复的版本你再试试

**Comment by ilharp** [comment]
这就奇怪了……那试试 v3 呢？

按理来说 Intel 6 代的 CPU 不会出现 TSC 问题的，这个情况很奇怪啊  并且我觉得也不像是 TSC 以外的问题

如果 v3 还有问题的话我一会给你做个 v3/v4 加装 TSC 修复的版本你再试试

**Comment by KillerJmc** [comment]
重新测试，还是闪退。

**Comment by ilharp** [comment]
打好了，这是 [打了 TSC 补丁的 v4](https://github.com/ilharp/surface-pro-4-hackintosh-monterey/archive/3675685f6eb66e0f0a5f7cefb8c8c5c31c48f8f2.zip) 和 [打了 TSC 补丁的 v3](https://github.com/ilharp/surface-pro-4-hackintosh-monterey/archive/e4bd74951c716cdd0f4cc8abefe156da4e6ff219.zip) 的版本，都可以测试下。不需要重装系统。

如果在启动过程中有报错的话可以告诉我；如果全部都是在 OOBE 阶段报错的话，说明你的设备固件可能有问题。你需要全新安装 Windows（使用最常规的方法就行），装好以后检查若干遍系统更新，确保固件都处于最新状态，然后再试试 Monterey + Release 里的原版 v4。

如果全都无效的话，可能是你的设备中奖了，你可以选择去 acidanthera 开 issue 看看能否解决。

**Comment by KillerJmc** [comment]
启动无报错，但是问题依旧新的v3, v4都不行，我的系统是最新状态，分区也都正常，efi也没有异常情况。

**Comment by ilharp** [comment]
那应该是设备中奖了，大概很难解决，我也没有什么其他的思路。

如果你愿意自己调试查看报错的话可以按照 [OpenCore Debugging](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html) 试试，但我这边应该很难能再帮到你了。

如果你拿到了 Kernel Log 或者其他的报错日志的话可以跟我说。

**Comment by KillerJmc** [comment]
好的谢谢你啦~

**Comment by Max-Hard** [comment]
您好，我也遇到了完全相同的问题，同为SurfacePro 4 ( i7-6650U ），现在有解决方案吗？

**Comment by Max-Hard** [comment]
网上所有成功案例都是 i5-6300U芯片的，i7不一定有希望了。不过我在网上找到了触摸屏驱动的办法，方便能使用的测试者：（远景论坛）https://bbs.pcbeta.com/viewthread-1912004-1-1.html

**Comment by Yotoile** [comment]
***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月7日 22:49
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ilharp/surface-pro-4-hackintosh-monterey] pro4 i7版本不兼容 (Issue #5)
        
      
    
  

网上所有成功案例都是 i5-6300U芯片的，i7不一定有希望了。不过我在网上找到了触摸屏驱动的办法，方便能使用的测试者：（远景论坛）https://bbs.pcbeta.com/viewthread-1912004-1-1.html

**Comment by Max-Hard** [comment]
@Yotolie：emmm……这是什么意思，我不太能看懂。

**Comment by Max-Hard** [comment]
还有人吗？
