### ISSUE TITLE
网络求助

### ISSUE THREAD

**Issue by Orangevvvv** [ilharp/surface-pro-4-hackintosh-monterey#6]
之前bigsur还好好的 昨天抽风试装了个monterey1.2.4 其他都正常就是网络蓝牙就不能用了。 
网络偏好设置里没有蓝牙和WIFI，想从小加号里添加结果根本没有WIFI或蓝牙的接口。
搜索引擎了半天没有解决办法，还望大佬抬一手帮忙看下是什么原因。
用也是COMFAST CF-811AC，在其他设备上试了网卡正常。

**Comment by ilharp** [comment]
要装 App 的~系统偏好设置里的设置是无效的~

App 在 [这里](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/releases) 可以下载，我的 README 里也有给链接哦~

下载安装之后重启就可以在任务栏上找到了~

如果还有什么问题的话可以跟我说~

**Comment by ilharp** [comment]
可能是我 README 里面没讲清楚吗……总之已经更新了下 README，现在注意事项里有对 Wi-Fi 的说明了！

**Comment by Orangevvvv** [comment]
解决了，原来是我自己的问题，下载错了，装了个不带OC的。 
感谢大佬秒回 谢谢谢谢谢！！！
另外再多问下 目前只有WIFI没有蓝牙是吧？

**Comment by ilharp** [comment]
是的  目前设备内置的 Wi-Fi 和蓝牙都无法驱动

能够使用 Wi-Fi 的原因是 COMFAST 开源了其驱动，Wireless-USB-OC-Big-Sur-Adapter 这个项目把驱动移植到了 Mac 平台上

如果以后出现 USB 蓝牙驱动移植到 Mac 上的话那也可以购买 USB 蓝牙使用，不过现在貌似并没有出现这样的东西
