### ISSUE TITLE
找不到触控板

### ISSUE THREAD

**Issue by chenyuhehe** [ilharp/surface-pro-4-hackintosh-monterey#7]
你好，我安装好以后在【系统偏好设置】里打开【触控板】选项显示找不到触控板，请问是哪里设置不对吗？

**Comment by ilharp** [comment]
请提供一下下面几个信息~

- 所安装的本项目的版本（是 `v4` 吗）？

- 所安装的 macOS 的版本（`关于此 Mac` 里显示的精确版本）

- 电脑是 sp4 8+256 吗？

**Comment by chenyuhehe** [comment]
安装的版本是v4的，我的macos版本是12.3.1，电脑是surface pro 4 i5cpu，8g内存、256硬盘

**Comment by ilharp** [comment]
尝试在右上角控制中心关闭蓝牙能否解决问题？我这边蓝牙设定是有一个「返回」按钮的。

**Comment by ilharp** [comment]
如果关闭蓝牙无法解决，可以试试下面的方法：

---

现在 `v4` 的触摸板驱动使用的是 [Xiashangning/BigSurface](https://github.com/Xiashangning/BigSurface) 魔改版 Voodoo 驱动，可能不兼容你的电脑。你可能需要换成官版 Voodoo 驱动。

我下面简单说一下操作方法：

1. 把 `config.plist` 里的 `BigSurface` 禁用，在 `505` 行改成 `false`

```diff
  <dict>
  	<key>Arch</key>
  	<string>Any</string>
  	<key>BundlePath</key>
  	<string>BigSurface.kext</string>
  	<key>Comment</key>
  	<string>The BigSurface Kext, Used to Enhance Keyboard and Touchpad</string>
  	<key>Enabled</key>
- 	<true/>
+ 	<false/>
  	<key>ExecutablePath</key>
  	<string>Contents/MacOS/BigSurface</string>
  	<key>MaxKernel</key>
  	<string></string>
  	<key>MinKernel</key>
  	<string></string>
  	<key>PlistPath</key>
  	<string>Contents/Info.plist</string>
  </dict>
```

3. 在 [这里](https://github.com/VoodooI2C/VoodooI2C/releases/tag/2.7) 找到 `VoodooI2C-2.7.zip` 下载，然后把 `Kexts` 文件夹下的这四个文件夹

```
VoodooGPIO.kext
VoodooI2CServices.kext
VoodooInput.kext
VoodooSerial.kext
```

删掉，最后把下载的官方文件夹放入。

**Comment by chenyuhehe** [comment]
好的，我试一下看看，谢谢！

**Comment by chenyuhehe** [comment]
你好，我尝试了控制台关闭蓝牙和替换驱动的方法，还是无法正常显示触控板配置界面，在鼠标和键盘的蓝牙设置里是有【返回】按钮的，但是触控板没有。会不会是我的macos 12.3.1系统有问题？

**Comment by ilharp** [comment]
我现在所在的版本也是 `12.3.1`。我认为已经可以排除 BigSurface 或系统本身出问题的可能性了。

你可以试一下把第 13 行的 DSDT 禁用掉。这个 DSDT 是我偷懒加进去的，之前也有人反映过这个 DSDT 可能有问题。

---

如果还不行的话，剩下的情况，90% 的可能性就是你设备的 GPI0 与大多数情况下的不一样。你需要参考 [这里](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad-methods/manual.html) 的教程手动打一份 `SSDT-GPI0.aml` 文件出来，并且在 `config.plist` 里加装上。记得详细阅读教程和教程里提到的所有链接。

**Comment by chenyuhehe** [comment]
好的，我研究一下试试看，谢谢
