### ISSUE TITLE
你好 我想问一下那个触摸可不可以通过桥接触摸板 实现I2C触摸 拥有和触摸板差不多的手势 这里单纯只是建议 作者可以尝试一下

### ISSUE THREAD

**Issue by lone0x0** [ilharp/surface-pro-4-hackintosh-monterey#8]

**Comment by ilharp** [comment]
你好  没有驱动  做不到的~

**Comment by lone0x0** [comment]
> 你好 没有驱动 做不到的~

https://www.pcbeta.com/archiver/tid-1856942.html?page=2 这里eif里边有驱动

**Comment by lone0x0** [comment]
https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1737992 你可以看看这篇 不是没有驱动 只是技术有限罢了

**Comment by ilharp** [comment]
> > 你好 没有驱动 做不到的~
> 
> [pcbeta.com/archiver/tid-1856942.html?page=2](https://www.pcbeta.com/archiver/tid-1856942.html?page=2) 这里eif里边有驱动

没有在你提供的链接里看到 sp4 触屏相关的驱动源码~如果你有找到相关驱动项目和代码的话可以直接发链接~
