### ISSUE TITLE
OpenCore Configurator was unable read because it isn’t in the correct format.  Please fix the following code before saving: Found non-key inside <dict> at line 1269

### ISSUE THREAD

**Issue by lone0x0** [ilharp/surface-pro-4-hackintosh-monterey#9]
![截屏2022-06-21 09 15 17](https://user-images.githubusercontent.com/78702504/174696159-6e829efe-5107-406a-ae57-04e60c0fe8c4.png)
你好 请问一下 这个怎么解决

**Comment by ilharp** [comment]
你好\~  是你所使用的 `config.plist` 文件出现了问题\~  需要自己查看文件的 1269 行进行修正哦\~

如果无法修正的话可以尝试将 1269 行附近的部分贴出来  我帮忙看看\~

**Comment by lone0x0** [comment]
> 你好~ 是你所使用的 `config.plist` 文件出现了问题~ 需要自己查看文件的 1269 行进行修正哦~
> 
> 如果无法修正的话可以尝试将 1269 行附近的部分贴出来 我帮忙看看~

1269那个应该是linux启动的efi文件 我把它删掉就好了 单系统问题不大
